[package]
name = "mkhelp"
version = "0.1.0"
authors = ["jlugao <joaolhullier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
regex = "1"
ansi_term = "0.12"
